export const GET_PODACT_DATA = 'GET_PODACT_DATA';
export const GET_PODACT_DATA_PENDING = 'GET_PODACT_DATA_PENDING';
export const GET_PODACT_DATA_REJECTED = 'GET_PODACT_DATA_REJECTED';
export const GET_PODACT_DATA_FULFILLED = 'GET_PODACT_DATA_FULFILLED';

export const ADD_CHOOSED_PRODUCT = 'ADD_CHOOSED_PRODUCT';
export const INCREASE_PRODUCT_AMOUNT = 'INCREASE_PRODUCT_AMOUNT';
export const DECREASE_PRODUCT_AMOUNT = 'DECREASE_PRODUCT_AMOUNT';